version: '3.8'

services:
  websee_cont:
    image: node:alpine
    container_name: websee_cont
    working_dir: /websee
    volumes:
      - /home/cybro/websee:/websee
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run test"
    restart: always
